import { PrintTemplate } from "../types";

export const initialPrintTemplates: PrintTemplate[] = [
  {
    id: "tpl-receipt-standard-a4",
    name: "Mẫu Phiếu Nhập Kho Tiêu Chuẩn (A4)",
    type: "GOODS_RECEIPT",
    isDefault: true,
    pageSize: "A4",
    orientation: "portrait",
    showLogo: true,
    title: "PHIẾU NHẬP KHO",
    companyName: "Công ty Cổ phần Nexus ERP",
    address: "Số 123 Đường Khu Công Nghệ Cao, Q.9, TP. Hồ Chí Minh",
    phone: "028 3829 1122",
    email: "contact@nexus.local",
    columns: {
      stt: true,
      sku: true,
      name: true,
      unit: true,
      quantity: true,
      unitPrice: true,
      totalPrice: true,
      note: true,
    },
    signatures: ["Người lập phiếu", "Người giao hàng", "Thủ kho", "Kế toán trưởng"],
    footerNotes: "Vui lòng kiểm tra kỹ số lượng và quy cách hàng hóa trước khi nhập kho.",
  },
  {
    id: "tpl-receipt-compact-a4",
    name: "Mẫu Phiếu Nhập Kho Rút Gọn (A4)",
    type: "GOODS_RECEIPT",
    isDefault: false,
    pageSize: "A4",
    orientation: "portrait",
    showLogo: false,
    title: "PHIẾU NHẬP KHO (RÚT GỌN)",
    companyName: "Nexus ERP Warehouse",
    address: "Kho trung tâm - Khu Công Nghệ Cao, TP.HCM",
    phone: "028 3829 1122",
    columns: {
      stt: true,
      sku: true,
      name: true,
      unit: true,
      quantity: true,
      unitPrice: false,
      totalPrice: false,
      note: false,
    },
    signatures: ["Người lập phiếu", "Thủ kho"],
    footerNotes: "Phiếu nhập lưu nội bộ bộ phận kho.",
  },
  {
    id: "tpl-issue-standard-a4",
    name: "Mẫu Phiếu Xuất Kho Tiêu Chuẩn (A4)",
    type: "GOODS_ISSUE",
    isDefault: true,
    pageSize: "A4",
    orientation: "portrait",
    showLogo: true,
    title: "PHIẾU XUẤT KHO",
    companyName: "Công ty Cổ phần Nexus ERP",
    address: "Số 123 Đường Khu Công Nghệ Cao, Q.9, TP. Hồ Chí Minh",
    phone: "028 3829 1122",
    email: "contact@nexus.local",
    columns: {
      stt: true,
      sku: true,
      name: true,
      unit: true,
      quantity: true,
      unitPrice: true,
      totalPrice: true,
      note: true,
    },
    signatures: ["Người lập phiếu", "Người nhận hàng", "Thủ kho", "Giám đốc"],
    footerNotes: "Hàng hóa xuất khỏi kho phải có đầy đủ chữ ký của thủ kho và người nhận.",
  },
  {
    id: "tpl-issue-internal-no-price",
    name: "Mẫu Phiếu Xuất Kho Nội Bộ (Ẩn giá)",
    type: "GOODS_ISSUE",
    isDefault: false,
    pageSize: "A4",
    orientation: "portrait",
    showLogo: true,
    title: "PHIẾU XUẤT KHO NỘI BỘ",
    companyName: "Công ty Cổ phần Nexus ERP",
    address: "Số 123 Đường Khu Công Nghệ Cao, Q.9, TP. Hồ Chí Minh",
    phone: "028 3829 1122",
    columns: {
      stt: true,
      sku: true,
      name: true,
      unit: true,
      quantity: true,
      unitPrice: false,
      totalPrice: false,
      note: true,
    },
    signatures: ["Người lập phiếu", "Thủ kho"],
    footerNotes: "Mẫu phiếu xuất dành cho điều chuyển nội bộ giữa các bộ phận.",
  },
];
